### ISSUE TITLE
JoinPoints on more than 2 connectors omits last strut when re-opening a file

### ISSUE THREAD

**Issue by david-hall** [vorth/vzome-core#5]
The problem appears to occur only when opening an existing file. JoinPoints works OK interactively.
Steps to reproduce problem:
1) From a new blank model, draw three blue struts from the ball at the origin. I drew one on the X axis, one on the Y axis, then one on the Z axis.
2) Select the three new balls, but not the one at the origin. I selected them in the same order that I drew them: X, then Y then Z.
3) Click on the topmost icon in the tool bar to "Join two or more selected balls".
4) This generates 3 new green struts that form an equilateral triangle. Including the three original blue struts, the model now consists of 4 balls and 6 struts forming a right angled tetrahedron.
5) Save the model as a .vZome file.
6) Open the .vZome file that was saved in the previous step.
7) Note that only two of the green struts are drawn. In my case, the strut joining the first ball I had selected (X) and the last one (Z) was the one that was missing.

**Comment by david-hall** [comment]
Note that if only two balls are selected so the JoinPoints command generates a single strut, then the saved file opens correctly. It's only when three or more balls are selected, generating more than one strut, that the problem occurs.

**Comment by vorth** [comment]
Good catch.  It happens in vZome 4.0, also, so it is an old bug.

If you use the menus, there are two forms of the join command, one that closes the loop and one that does not.  Looks like the mode attribute is not getting saved with the right value, in the XML.

**Comment by vorth** [comment]
Found it: JoinPoints.java, line 36.  I used to use XOM, which would give a null attribute value string.  DOM, however, returns the empty string.

There are very likely other bugs in this pattern.
